language: node_js
node_js:
  - "8"

services:
  - postgresql

cache:
  directories:
    - "node_modules"

before_install:
  - "npm install -g npm"
before_script:
  - "npm install"
  - "psql -c 'create database travis_ci_test;' -U postgres"
