language: node_js
node_js:
  - "8"

services:
  - postgresql

cache:
  directories:
    - "node_modules"
env:
  global:
    - DB_HOST=localhost
    - DB_PORT=5432
    - DB_NAME=queue
    - DB_USER=test
    - DB_PASS=qwerty
    - DEBUG=cli
    - HTTP_PROTOCOL=http://
    - HTTP_HOST=localhost
    - HTTP_PORT=8081
    - SOCKET_PORT = 9003
    - MOCHAWESOME_REPORTDIR=./tests/reports/
    - MOCHAWESOME_AUTOOPEN=false

before_install:
  - "npm install -g npm"

before_script:
  - psql -c "CREATE DATABASE queue;" -U postgres
  - psql -c "CREATE USER test WITH PASSWORD 'qwerty';" -U postgres
  - "npm install"
